name: multiple_stream_builder
description: Widgets for avoiding nested StreamBuilder
version: 0.0.1
homepage: https://github.com/glitchedmob/flutter_multiple_stream_builder

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  tuple: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
