name: multiple_stream_builder
description: Flutter widgets to replace multiple nested StreamBuilder widgets
version: 1.1.1
homepage: https://github.com/glitchedmob/flutter_multiple_stream_builder

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
